Redisgraph use actor interfaces
wasmCloud/capability-providers pull request #21
Opened 2021-01-20 19:09 UTC by brooksmtownsend

This PR uses the graphdb interface from https://github.com/wasmCloud/actor-interfaces/pull/20/files as well as the `actor-core` interface to rewrite the redisgraph provider and actor API.

2021-01-20 19:14 UTC, brooksmtownsend commented
Pending merge https://github.com/wasmCloud/actor-interfaces/pull/20 and crates.io releases, I do have `git` dependencies scattered around here.

2021-01-25 21:53 UTC, autodidaddict requested changes
I think the only thing that seems out of place here is that the query wrapper (redisgraph-actor) code should be inside the actor interface, and not inside a redis-specific repository.

2021-01-25 21:53 UTC, autodidaddict commented on redisgraph/crates/wasccgraph-actor/Cargo.toml
> +name = "redisgraph-actor"
I'm confused here. If we have the actor interface in `actor-interfaces/graphdb` , then why do we have another graph actor API that's specific to redis?

We should have a vendor-neutral graphdb actor interface in the actor-interfaces repository, and then we should have the stuff that _only_ applies to Redis in the redisgraph repository (the capability provider implementation).

2021-01-25 21:53 UTC, autodidaddict commented on redisgraph/crates/wasccgraph-actor/src/conversions.rs
> +use crate::client_type_error;
Again, this stuff belongs in the guest feature of the `actor_graphdb` crate, as none of this is Redis-specific...this abstraction that allows for the tuple-based query of a resultset should be available to all actors using graphdb, regardless of whether the implementation is Neo4j or redisgraph, etc.

2021-02-01 15:59 UTC, brooksmtownsend commented
@autodidaddict ready for review here, tests failing because of relative dependencies, pending https://github.com/wasmCloud/actor-interfaces/pull/20 merge

2021-02-02 21:30 UTC, autodidaddict approved these changes

2021-02-02 22:08 UTC, merged