Http client 0.15
wasmCloud/capability-providers pull request #26
Opened 2021-02-04 20:43 UTC by brooksmtownsend

- Updated to use http-client actor interface (will fail CI/CD since the interface isn't published yet)
- Updated tests accordingly
- Updated dependencies, namely Tokio `0.2` -> `1.1.1`

2021-02-04 20:44 UTC, brooksmtownsend commented
Not ready to be merged until https://github.com/wasmCloud/actor-interfaces/pull/37 is merged

2021-02-04 20:49 UTC, autodidaddict requested changes

2021-02-04 20:49 UTC, autodidaddict commented on http-client/Cargo.toml
> +repository = "https://github.com/wasmcloud/http-client-provider"
this URL is incorrect, it should be https://github.com/wasmcloud/capability-providers

2021-02-04 20:49 UTC, autodidaddict commented on http-client/src/lib.rs
> +const REVISION: u32 = 1;
as per other reviews, version and revision don't need to be constants anymore.

2021-02-11 16:00 UTC, autodidaddict requested changes

2021-02-11 16:00 UTC, autodidaddict commented on http-client/src/http_client.rs
> +        "PUT" => Ok(client.put(&req.url)),
The put doesn't appear to submit a body. `PUT` usually requires content. I know this appears to have been broken in the original version of this provider, too.

2021-02-11 16:00 UTC, autodidaddict commented on http-client/src/http_client.rs
> +            let r = client.post(&req.url).body(req.body);
This let should've been marked by clippy as superfluous. Same with the one on line 56.

2021-02-11 16:00 UTC, autodidaddict commented on http-client/src/lib.rs
> +        todo!()
This will cause a runtime exception when it hits. We should remove and replace with a no-op.

2021-02-11 18:13 UTC, merged