Support for aarch64-apple-darwin
wasmCloud/capability-providers pull request #71
Opened 2021-04-23 11:39 UTC by matthewtgilbride

2021-04-23 11:51 UTC, brooksmtownsend commented
@ChrisRx do we support `aarch64-apple-darwin` off of your fork of `cross`? I suppose related question @matthewtgilbride, were you able to verify that this worked by building with the cross image? I can try on my computer once I'm on for the day to give it a shot.

I think you're correct here though, this is what we'll want to do to support the M1 machines for all capability providers 😄

2021-04-23 11:57 UTC, matthewtgilbride commented
@brooksmtownsend I created the PR and immediately grabbed my work (non-M1) laptop assuming no one was up yet 😆 

I'll give it a try at lunch and report back.

2021-04-24 17:00 UTC, matthewtgilbride commented
@brooksmtownsend I run into local gcc issues trying to build the whole project from M1.  Was about to try and build from an x86 machine but you mention @ChrisRx 's fork of cross, which I assume is this? https://github.com/ChrisRx/cross

2021-04-26 14:49 UTC, brooksmtownsend commented
I think the main thing we're missing here is the `aarch64-apple-darwin` docker image, cross works by running the `cargo build` step in a container that matches that arch/os pair, and the `x86_64-apple-darwin` part works because that image exists (thanks to @ChrisRx). We may need to add in that container ourselves, unfortunately the cross maintainers haven't merged in that PR to the main branch yet

2021-04-27 14:14 UTC, brooksmtownsend commented
@matthewtgilbride Quick question, to clarify, are you able to build `http-server` with a straight up `cargo build` on the M1?

2021-04-28 12:59 UTC, autodidaddict approved these changes

2021-04-28 13:13 UTC, brooksmtownsend requested changes

2021-04-28 13:13 UTC, brooksmtownsend commented on Cross.toml
> +image = "criticalstack/cross:aarch64-apple-darwin"
We're going to want to update the `aarch64-apple-darwin` image to something that actually exists, and we're going to have to verify it works before we merge this in. Currently, the `criticalstack/cross:aarch64-apple-darwin` image doesn't exist and we need to find out if we can actually create that image

2021-04-28 13:13 UTC, brooksmtownsend commented on http-server/Cross.toml
> +image = "criticalstack/cross:aarch64-apple-darwin"
Same comment as above

2021-04-28 13:56 UTC, brooksmtownsend commented
Because @ChrisRx has done the hard part with https://github.com/ChrisRx/cross-images, I suggest we just fork that to the wasmcloud repository and update the images accordingly. For now we can just update the x86_64-linux one as that's the only image giving us issues. Thoughts @autodidaddict ?

2021-04-28 15:40 UTC, autodidaddict commented
Make it so

2021-05-05 11:38 UTC, autodidaddict commented
What's the status on this?

2021-05-05 12:58 UTC, brooksmtownsend commented
Looks like my previous comment was in reference to a different issue. For this, we'll need to:

- [ ] Fork criticalstack/cross to wasmcloud repo
- [ ] duplicate https://github.com/ChrisRx/cross-images/blob/main/Dockerfile.x86_64-apple-darwin and modify for `aarch64-apple-darwin`
- [ ] Ensure the above works
- [ ] Release our images to our dockerhub.

I haven't performed any of these steps, but I'll get started on steps 1+2. Will likely need @matthewtgilbride to test running the parJEEzy afterwards

2021-05-05 13:00 UTC, brooksmtownsend commented
I'm not 100% sure that this will work, https://github.com/tpoechtrager/osxcross#what-is-the-goal-of-osxcross states that you can target `aarch64` with it so in theory we should be able to provide this.

2021-05-13 15:12 UTC, autodidaddict commented
@brooksmtownsend status on this?

2021-05-13 15:16 UTC, brooksmtownsend commented
I've got the docker images ready, was planning on putting a PR into @matthewtgilbride 's fork today once I can verify that it builds well 👍🏻 (and once @matthewtgilbride can verify that the parJEEzy works)

2021-05-14 13:57 UTC, brooksmtownsend commented
RE: my comment yesterday, @matthewtgilbride was able to confirm that the aarch64-apple-darwin is working for him 🚀 Barring an update to the blobstore contract, I've submitted https://github.com/matthewtgilbride/capability-providers/pull/3, which will get merged in, and then we can merge this into main.

2021-05-17 20:59 UTC, brooksmtownsend approved these changes
Once tests pass, LGTM 👍🏻

2021-05-17 21:01 UTC, merged